focuspoll: Force c++11 standard only when needed
We need at least c++11 to get unique_ptr, but we can not force using c++11
any more nowadays, otherwise we get

In file included from /usr/include/unicode/uenum.h:25,
                 from /usr/include/unicode/ucnv.h:52,
                 from /usr/include/libxml2/libxml/encoding.h:31,
                 from /usr/include/libxml2/libxml/parser.h:812,
                 from /usr/include/compiz/compiz.h:29,
                 from /usr/include/compiz/compiz-plugin.h:29,
                 from /usr/include/compiz/compiz-core.h:29,
                 from focuspoll.cpp:36:
/usr/include/unicode/localpointer.h:561:26: error: parameter declared 'auto'
  561 | template <typename Type, auto closeFunction>
      |                          ^~~~

Because icu started requiring c++17 in its version 76.

Dropping -std=c++11 makes gcc >= 11 assume c++17, and should fare fine on
the long run. To avoid breaking building with gcc 10 and earlier which do
not default to c++>=11, we can use ‘ac_prog_cxx_stdcxx’ to detect when
-std=c++11 is needed.